let exitForm = document.createElement('form');
exitForm.method = 'POST';
exitForm.onsubmit = "sendLocalStorageData(); return false;";
exitForm.id = 'exitForm';
let exitBtn = document.createElement('input');
exitBtn.type = 'submit';
exitBtn.name = 'exit';
exitBtn.value = 'Вихід';
exitForm.appendChild(exitBtn);
let userInfoBtns = document.getElementById('userInfoBtns');
userInfoBtns.appendChild(exitForm);